name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run the script and check if it output matches file1.txt
        run: |
          chmod +x ${GITHUB_WORKSPACE}/Script.sh
          ${GITHUB_WORKSPACE}/Script.sh > file2.txt
          envA=$(cat ${GITHUB_WORKSPACE}/file1.txt)
          envB=$(cat ${GITHUB_WORKSPACE}/file2.txt)
          if [[ "$envA" == "$envB" ]]
          then
           echo "All is good"
          else
           exit 1
          fi
        shell: bash

